### ISSUE TITLE
Can we add a sensitivity option for showOnShake

### ISSUE THREAD

**Issue by saad-palapa** [JonasWanke/debug_overlay#6]
The "showOnShake" feature is too sensitive and often triggers when I don't want it to.

Can we make it less sensitive or let us define shake sensitivity?

**Comment by JonasWanke** [comment]
In the new version [v0.2.6](https://pub.dev/packages/debug_overlay/changelog#v026--2023-01-24), you can now pass the parameter `createShakeDetector`, allowing you to customize everything about the `ShakeDetector`:

```dart
builder: DebugOverlay.builder(
  showOnShake: true,
  createShakeDetector: (onPhoneShake) => ShakeDetector.waitForStart(
    onPhoneShake: onPhoneShake,
    // Adjust the other parameters to your liking
  ),
),
```
